name: Push and Deploy Serverless function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ env.prod.YC_TOKEN }}
          function_id: ${{ env.prod.YC_FUNCTION_ID }}
          runtime: 'python38'
          entrypoint: 'index.handler'
          environment: TG_TOKEN=${{ env.prod.TG_TOKEN }},YC_ACCESS_KEY=${{ env.prod.YC_ACCESS_KEY }},YC_PRIVATE_KEY=${{ env.prod.YC_PRIVATE_KEY }},DB_ENDPOINT=${{ env.prod.DB_ENDPOINT }},DB_DATABASE=${{ env.prod.DB_DATABASE }}
          memory: '128'
          execution_timeout: '5'
          service_account: ${{ env.prod.YC_SERVICE_ACCOUNT }}
          source: '.'
          exclude: '.git/,.github/,/.gitignore,.README.md,.vscode,.devcontainer'